# config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $fourEyesPrinciple: '%diversworld_contao_editorial_workflow.four_eyes_principle%'
            $enabledTables: '%diversworld_contao_editorial_workflow.enabled_tables%'

    Diversworld\ContaoEditorialWorkflow\:
        resource: ../src/
        exclude: ../src/{DependencyInjection,Model,Session}

    Diversworld\ContaoEditorialWorkflow\EventListener\NotificationCenter\NotificationTypeListener:
        tags:
            - { name: kernel.event_listener, event: terminal42_notification_center.get_token_definitions }

        # Add a session bag
    diversworld.contao_editorial_workflow.session.factory:
        class: Diversworld\ContaoEditorialWorkflow\Session\SessionFactory
        decorates: session.factory
        arguments:
            - '@diversworld.contao_editorial_workflow.session.factory.inner'
            - '@diversworld.contao_editorial_workflow.session.attribute.array_attribute_bag'

    diversworld.contao_editorial_workflow.session.attribute.array_attribute_bag:
        class: Diversworld\ContaoEditorialWorkflow\Session\Attribute\ArrayAttributeBag
        arguments:
            - _diversworld_contao_editorial_workflow_attributes
        calls:
            - [ setName, [ diversworld_contao_editorial_workflow ] ]

    Diversworld\ContaoEditorialWorkflow\NotificationCenter\WorkflowNotificationType:
        tags:
            - { name: terminal42_notification_center.notification_type, type: workflow_status_change }
            - { name: terminal42_notification_center.notification_type, type: workflow_review_requested }
            - { name: terminal42_notification_center.notification_type, type: workflow_approved }
            - { name: terminal42_notification_center.notification_type, type: workflow_rejected }

    Diversworld\ContaoEditorialWorkflow\Dashboard\ApprovalDashboard:
        public: true
        arguments:
            $csrfTokenManager: '@contao.csrf.token_manager'

    Diversworld\ContaoEditorialWorkflow\EventListener\DashboardListener:
        public: true
