# config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $fourEyesPrinciple: '%diversworld_contao_editorial_workflow.four_eyes_principle%'
            $enabledTables: '%diversworld_contao_editorial_workflow.enabled_tables%'
            $csrfTokenName: '%contao.csrf_token_name%'
            $container: '@service_container'

    Diversworld\ContaoEditorialWorkflow\:
        resource: ../src/
        exclude:
            - ../src/DependencyInjection
            - ../src/Model
            - ../src/Session
            - ../src/NotificationCenter/WorkflowNotificationType.php

    Diversworld\ContaoEditorialWorkflow\Workflow\WorkflowManager:
        public: true
        arguments:
            $notificationCenter: '@?terminal42_notification_center.notification_center'

    # Add a session bag
    diversworld.contao_editorial_workflow.session.factory:
        class: Diversworld\ContaoEditorialWorkflow\Session\SessionFactory
        decorates: session.factory
        arguments:
            - '@diversworld.contao_editorial_workflow.session.factory.inner'
            - '@diversworld.contao_editorial_workflow.session.attribute.array_attribute_bag'

    diversworld.contao_editorial_workflow.session.attribute.array_attribute_bag:
        class: Diversworld\ContaoEditorialWorkflow\Session\Attribute\ArrayAttributeBag
        arguments:
            - _diversworld_contao_editorial_workflow_attributes
        calls:
            - [ setName, [ diversworld_contao_editorial_workflow ] ]

    # Approval Dashboard
    Diversworld\ContaoEditorialWorkflow\Dashboard\ApprovalDashboard:
        public: true

    Diversworld\ContaoEditorialWorkflow\Backend\WorkflowApprovalsModule:
        public: true

    Diversworld\ContaoEditorialWorkflow\EventListener\DashboardListener:
        public: true

    Diversworld\ContaoEditorialWorkflow\EventListener\DataContainer\WorkflowLogListener:
        public: true
